version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    restart: always
    ports:
      - "3000:3000"
      - "5556:5555"
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/homolog
      - APP_PORT=3000
    depends_on:
      - db

volumes:
  pgdata:
